-- 회원가입, 게시글 등록, 입금... 같은 실생활 관련된 것.

-- 기존의 DEPT 테이블을 복사해서 dept_temp 테이블 생성
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;

-- 현재 테이블 조회
SELECT *
FROM DEPT_TEMP;

-- 데이터 추가하기(방법 1)
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(50, 'DATABASE', 'SEOUL');

-- 데이터 추가하기(방법 2)
INSERT INTO DEPT_TEMP VALUES(60, 'NETWORK', 'BUSAN');

-- 에러 
-- INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(50, 'DATABASE');
-- INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(500, 'DATABASE', 'SEOUL');

--NULL 삽입하기 
-- 명시적으로 NULL 삽입.
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(70, 'DATABASE', NULL);
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(80, 'DATABASE', ' ');

-- 묵시적으로 NULL 삽입.
INSERT INTO DEPT_TEMP(DEPTNO, LOC) VALUES(90, 'INCHEON');

-- EMP테이블을 복사하여 EMP_TENP 테이블 생성
CREATE TABLE EMT_TEMP AS SELECT * FROM EMP;

-- 테이블 삭제
DROP TABLE EMP_TEMP;
DROP TABLE EMT_TEMP; -- 이거로 했었음.

-- EMP테이블을 복사하여 EMP_TENP 테이블 생성하되 구조만 복사하기
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP WHERE 1<>1;
SELECT * FROM EMP_TEMP;

DESC EMP_TEMP;
INSERT INTO EMP_TEMP(empno,ename,job,mgr,hiredate,sal,comm,deptno)
VALUES(9999,'홍길동','PRESIDENT',NULL,'2020-11-09',4000,NULL,10);
INSERT INTO EMP_TEMP(empno,ename,job,mgr,hiredate,sal,comm,deptno)
VALUES(8888,'성춘향','MANAGER',NULL,'2020-10-08',3000,NULL,10);

-- 최종반영
COMMIT;

INSERT INTO EMP_TEMP(empno,ename,job,mgr,hiredate,sal,comm,deptno)
VALUES(7777,'유승호','MANAGER',NULL,TO_DATE('07/01/2010', 'DD/MM/YYYY'),4000,NULL,20);

INSERT INTO EMP_TEMP(empno,ename,job,mgr,hiredate,sal,comm,deptno)
VALUES(6666,'이순신','MANAGER',NULL,SYSDATE,3000,NULL,20);

-- EMP 테이블에서 SALGRADE 테이블을 참조하여 급여 등급이 1등급인 사원만큼
-- EMP_TEMP 테이블에 추가하고 싶다면?
-- 서브쿼리로 작성하기(데이터가 추가되는 테이블의 열 개수와 서브쿼리의 열 개수가 일치)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 1;

-- COMMIT;










