-- 제약조건(DDL 작성)
-- 1. NOT NULL
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20));

--INSERT INTO TABLE_NOTNULL VALUES('hong1234','hong1234');

INSERT INTO TABLE_NOTNULL(LOGIN_ID,LOGIN_PWD)
VALUES('hong1234','hong1234');

INSERT INTO TABLE_NOTNULL(LOGIN_ID,LOGIN_PWD)
VALUES('KANG1234', NULL);

SELECT * FROM TABLE_NOTNULL;

UPDATE TABLE_NOTNULL SET LOGIN_PWD=NULL WHERE LOGIN_ID='hong1234';

SELECT * FROM TABLE_NOTNULL;

-- 제약조건 확인하기
SELECT * FROM USER_CONSTRAINTS;

-- 제약조건 지정하기
CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBL_NN_LGIND_NN NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBL_NN_LGPWD_NN NOT NULL,
    TEL VARCHAR2(20));

-- 제약조건 추가
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL NOT NULL);
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL CONSTRAINT TBL_NN_TEL_NN NOT NULL);
-- 제약조건 이름 변경
ALTER TABLE TABLE_NOTNULL2 RENAME CONSTRAINT SYS_C0011154 TO TBL_NN_TEL_NN;

-- 제약조건 삭제
ALTER TABLE TABLE_NOTNULL2 DROP CONSTRAINT TBL_NN_TEL_NN;

UPDATE TABLE_NOTNULL SET TEL='010-1111-1111' WHERE LOGIN_ID='hong1324';
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL);

-- 2. unique : 중복되지 않는 값

CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20));

INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PWD,TEL)
VALUES('TEST_ID01', 'PWD01','010-1234-1234');
INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PWD,TEL)
VALUES('TEST_ID02', 'PWD01','010-1234-1234');

SELECT * FROM TABLE_UNIQUE;

-- 제약조건 확인하기 // 작업은 동일
SELECT * FROM USER_CONSTRAINTS;

-- 제약조건 추가
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL NOT NULL);
ALTER TABLE TABLE_NOTNULL2 MODIFY(TEL CONSTRAINT TBL_NN_TEL_NN NOT NULL);
-- 제약조건 이름 변경
ALTER TABLE TABLE_NOTNULL2 RENAME CONSTRAINT SYS_C0011154 TO TBL_NN_TEL_NN;

-- 제약조건 삭제
ALTER TABLE TABLE_NOTNULL2 DROP CONSTRAINT TBL_NN_TEL_NN;


--오류 뜸.
CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE,
    LOGIN_PWD VARCHAR2(20) TBLUNQ2_LGNPWD_NN NOT NULL,
    TEL VARCHAR2(20));
    
    
-- 3. PRIMARY KEY(NOT NULL + UNIQUE) : 기본키

CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20));
    
SELECT * FROM USER_CONSTRAINTS;
    
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID01', 'PWD01','010-1234-1234');
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD01','010-1234-1234');
    
--오류남
CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LOGID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20));

-- 제약조건만 모아서 주기
CREATE TABLE TABLE_CONSTRAINT(
    ID NUMBER(6),
    NAME VARCHAR2(10),
    ADDR VARCHAR2(20),
    TEL VARCHAR2(20),
    CONSTRAINT TBL_ID_PK PRIMARY KEY(ID),
    CONSTRAINT TBL_TEL_UNQ UNIQUE(TEL)
);

-- 4. FOREIGN KEY(외래키) : 서로 다른 테이블 간 관계 정의
CREATE TABLE DEPT_FK(
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(14),
LOC VARCHAR2(13));

CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO));

/*CONSTRAINT DEPTFK_DEPTNO_PK 키 이름이 동일해서 에러난 거임. 위에 DEPT_FK  그대로 가져오느라...
EMPNO NUMBER(4) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO));
*/
INSERT INTO DEPT_FK VALUES(50,'DATABASE','SEOUL');

INSERT INTO EMP_FK VALUES(1111,'홍길동','clerk','7788','2019-02-13',1200,null,50);

DELETE FROM DEPT_FK WHERE DEPTNO=50;

DROP TABLE EMP_FK;

CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
ON DELETE CASCADE);

/*
CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK
REFERENCES DEPT_FK(DEPTNO) ON DELETE CASCADE);
*/
-- ON DELETE CASCADE : 부모키가 제거될 때 자식키도 같이 
-- ON DELETE SET NULL : 부모키가 제거될 때 자식키의 값은 NULL로 변경

INSERT INTO EMP_FK
VALUES(1111,'홍길동','clerk','7788','2019-02-13',1200,null,50);

DELETE FROM DEPT_FK WHERE DEPTNO=50;

SELECT * FROM EMP_FK;
SELECT * FROM DEPT_FK;

DROP TABLE EMP_FK;
DROP TABLE DEPT_FK;


CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
ON DELETE SET NULL);
/*
CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK
REFERENCES DEPT_FK(DEPTNO) ON DELETE SET NULL);
*/

INSERT INTO DEPT_FK VALUES(50,'DATABASE','SEOUL');

INSERT INTO EMP_FK
VALUES(1111,'홍길동','clerk','7788','2019-02-13',1200,null,50);

DELETE FROM DEPT_FK WHERE DEPTNO=50;

-- 5. CHECK : 열에 저장할 수 있는 값의 범위 또는 패턴 정의
CREATE TABLE TABLE_CHECK(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGPD_CK CHECK (LENGTH(LOGIN_PWD)>3),
    TEL VARCHAR2(20));
    
INSERT INTO TABLE_CHECK VALUES('TEST_ID','1234','010-1234-5678');

-- 6. DEFAULT : 기본값 정하기
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLDF_LOGID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2(20));

DESC TABLE_DEFAULT;

INSERT INTO TABLE_DEFAULT VALUES('TEST_ID',NULL,'010-1234-5678');
INSERT INTO TABLE_DEFAULT VALUES('TEST_ID2',4567,'010-1234-5678');
INSERT INTO TABLE_DEFAULT(LOGIN_ID,TEL) VALUES('TEST_ID3','010-1234-5678');

SELECT * FROM TABLE_DEFAULT;















    