CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;

INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');

commit;

select *from dept_tcl;

rollback;

-- 하나의 트랜잭션 생성
INSERT INTO DEPT_TCL VALUES(60,'NETWORK','BUSAN');
UPDATE DEPT_TCL SET LOC='SEOUL' WHERE DPTNO=40;
DELETE FROM DEPT_TCL WHERE DNAME='RESERACH';
SELECT * FROM DEPT_TCL;

COMMIT;






